#!/bin/sh

cd "$(dirname "$0")" || exit $?
find . -mtime -7 \( -iname \*.flac -o -iname \*.mp3 -o -iname \*.m4a -o -iname \*.dsf \) \
    | sed -e 's#^\./##; s#/[^/]*$##' \
    | uniq \
    | tr '\n' '\0' \
    | xargs -0 ls -Adlhrt
