#!/bin/sh

. "$(dirname "$0")/common-music.sh"
. "$(dirname "$0")/trap.sh"

case "$BASH_VERSION" in
    '')
        trap 'rm -f $cleanfiles; on_exit' EXIT
        ;;
    *)
        trap 'rm -f $cleanfiles' EXIT
        ;;
esac
# trap 'rm -f $cleanfiles' EXIT

PATH="$(cd "$(dirname "$0")" && pwd):$PATH"

set -e

usage () {
    echo >&2 "${0##*/} [-n] SOURCE_DIR [SOURCE_DIR..]"
    exit 2
}

alias link='ln -fv'

if [ $# -eq 0 ]; then
    set -- .
fi

dry_run=0
while getopts nh opt; do
    case "$opt" in
        n)
            dry_run=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi

audiofiles="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
otherfiles="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
cleanfiles="$audiofiles"
trap 'rm -f "$audiofiles"' INT TERM

for source_dir; do
    if [ ! -e "$source_dir" ]; then
        continue
    fi
    source_dir="${source_dir%/}"
    music_find "$source_dir" >"$audiofiles"
    while read -r fn; do
        newfn="$(get_new_filename "$fn" "$source_dir")"
        if [ "$fn" != "$newfn" ] && ! [ -e "$newfn" ]; then
            newfndir="$(dirname "$newfn")"
            if [ $dry_run -eq 0 ]; then
                mkdir -p "$newfndir"
            fi

            if [ $dry_run -eq 1 ]; then
                echo "$fn -> $newfn"
            else
                mv -v "$fn" "$newfn"
            fi

            oldfndir="$(dirname "$fn")"
            if ! echo "$oldfndir" | grep -qix "$newfndir"; then
                # Non-audio files
                nonmusic_find "$oldfndir" \
                    | while read -r efn; do
                        newefn="$newfndir/${efn##*/}"
                        if ! grep -qx "$efn" "$otherfiles" && ! [ -e "$newefn" ]; then
                            echo "$efn" >>"$otherfiles"
                            if [ $dry_run -eq 1 ]; then
                                echo "$efn -> $newefn"
                            else
                                mv -v "$efn" "$newefn"
                            fi
                        fi
                    done
                remove-empty-dirs "$oldfndir"
            fi
        fi
    done <"$audiofiles"
done
