#!/bin/sh

[ -e /Volumes/DAP ] \
    && wait-for-process split-singles \
    && rsync -avLP --exclude .Trashes --exclude .fseventsd --exclude .DS_Store --exclude ._\* --exclude .Spotlight-V100 --exclude update\* --delete /Volumes/Data/DAP\ Music/Organized/ /Volumes/DAP/ \
    && hdiutil eject /Volumes/DAP
