#!/bin/sh
# shellcheck disable=SC2154

export LC_ALL=en_US.utf-8

set -e

scriptdir="$(cd "$(dirname "$0")" && pwd)"
PATH="$scriptdir/../scripts:$PATH"

usage() {
    cat >&2 <<END
    ${0##*/} [options] [PLAYLIST_DIR]

    PLAYLIST_DIR defaults to $playlistdir

    Options:
    -h    Show this usage info
    -e    Write an extended m3u
END
    exit 2
}

playlistdir=./_Playlists
extm3u=
while getopts ep:h opt; do
    case "$opt" in
        e)
            extm3u=1
            ;;
        p)
            playlistdir="$OPTARG"
            if ! [ -d "$playlistdir" ]; then
                echo >&2 "Error: OUTPUT_DIR $playlistdir must be an existing directory"
                usage
            fi
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

cd "$scriptdir"
mkdir -p "$playlistdir"
find ../Playlists -type f \
    | while read -r playlist; do
        dir="$(dirname "${playlist#../Playlists/}")"
        destdir="$playlistdir/$dir"
        if [ "$dir" != "." ]; then
            rel="../$(echo "$dir/" | sed -e 's#[^/]*##g; s#/#../#g')"
        else
            rel=../
        fi
        echo >&2 "Processing $dir/${playlist##*/}.m3u8"
        mkdir -p "$destdir"
        rockuefort-gen-m3u -w ${extm3u:+-e} -r "$scriptdir/" -p "${rel%/}" -d "$destdir" "$playlist"
    done
